name: CI/CD with Flux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create .kube Directory
      run: mkdir -p $HOME/.kube

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    - name: Install Flux
      run: |
        curl -s https://fluxcd.io/install.sh | sudo bash

    - name: Bootstrap Flux
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_1 }}
      run: |
        flux bootstrap github \
          --owner=karthikkvssk \
          --repository=my-k8s-config \
          --branch=main \
          --path=./clusters/my-cluster \
          --token=${GITHUB_TOKEN}

    - name: Verify Flux Installation
      run: kubectl get pods -n flux-system

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f clusters/my-cluster
